import { PrismaClient } from "@prisma/client";
const prisma = new PrismaClient();

async function main() {
  const vinyls = [
    {
      artist: "Alabama Shakes",
      album: "Sound and Color",
      year: 2015,
      timesPlayed: 0,
      genre: "Soul, Southern Rock",
      artworkPath: "/uploads/alabamashakes_soundcolor.jpg",
    },
    {
      artist: "ABBA",
      album: "Gold Greatest Hits",
      year: 1992,
      timesPlayed: 0,
      genre: "Pop, Disco, Europop",
      artworkPath: "/uploads/abba_goldgreatesthits.jpg",
    },
    {
      artist: "All Them Witches",
      album: "Live on the Internet",
      year: 2022,
      timesPlayed: 0,
      genre: "Stoner Rock, Psychedelic Rock",
      artworkPath: "/uploads/allthemwitches_liveontheinternet.jpg",
    },
    {
      artist: "Aurora",
      album: "The Gods We Can Touch",
      year: 2022,
      timesPlayed: 0,
      genre: "Pop, Electropop",
      artworkPath: "/uploads/aurora_thegodswecantouch.jpg",
    },
    {
      artist: "The Beatles",
      album: "Sgt. Pepper's Lonely Hearts Club Band",
      year: 1967,
      timesPlayed: 0,
      genre: "Rock, Psychedelic Rock",
      artworkPath: "/uploads/thebeatles_sgtpepperslonelyhear.jpg",
    },
    {
      artist: "The Black Keys",
      album: "Live at Beachland Tavern",
      year: 2002,
      timesPlayed: 0,
      genre: "Blues Rock, Garage Rock",
      artworkPath: "/uploads/theblackkeys_liveatbeachlandtaver.jpg",
    },
    {
      artist: "Bruce Springsteen",
      album: "Born in the USA",
      year: 1984,
      timesPlayed: 0,
      genre: "Rock, Heartland Rock",
      artworkPath: "/uploads/brucespringsteen_bornintheusa.jpg", // Stopped here
    },
    {
      artist: "Kate Bush",
      album: "The Whole Story",
      year: 1986,
      timesPlayed: 0,
      genre: "Art Pop, Progressive Pop",
      artworkPath: "/uploads/katebush_thewholestory.jpg",
    },
    {
      artist: "Kate Bush",
      album: "Hounds of Love",
      year: 1985,
      timesPlayed: 0,
      genre: "Art Pop, Progressive Pop",
      artworkPath: "/uploads/katebush_houndsoflove.jpg",
    },
    {
      artist: "David Bowie",
      album: "Let's Dance",
      year: 1983,
      timesPlayed: 0,
      genre: "Pop, Rock",
      artworkPath: "/uploads/davidbowie_letsdance.jpg",
    },
    {
      artist: "Charlie Crockett",
      album: "The Valley",
      year: 2019,
      timesPlayed: 0,
      genre: "Country, Blues",
      artworkPath: "/uploads/charliecrockett_thevalley.jpg",
    },
    {
      artist: "Charlie Crockett",
      album: "Welcome to Hard Times",
      year: 2020,
      timesPlayed: 0,
      genre: "Country, Blues",
      artworkPath: "/uploads/charliecrockett_welcometohardtimes.jpg",
    },
    {
      artist: "Big Brother and the Holding Company",
      album: "Cheap Thrills",
      year: 1968,
      timesPlayed: 0,
      genre: "Blues Rock, Psychedelic Rock",
      artworkPath: "/uploads/bigbrother_cheapthrills.jpg",
    },
    {
      artist: "Creedence Clearwater Revival",
      album: "Cosmo's Factory",
      year: 1970,
      timesPlayed: 0,
      genre: "Rock, Swamp Rock",
      artworkPath: "/uploads/ccr_cosmosfactory.jpg",
    },
    {
      artist: "Daft Punk",
      album: "Alive 2007",
      year: 2007,
      timesPlayed: 0,
      genre: "Electronic, House",
      artworkPath: "/uploads/daftpunk_alive2007.jpg",
    },
    {
      artist: "John Denver",
      album: "An Evening with John Denver",
      year: 1975,
      timesPlayed: 0,
      genre: "Folk, Country",
      artworkPath: "/uploads/johndenver_anevening.jpg",
    },
    {
      artist: "Dua Lipa",
      album: "Future Nostalgia",
      year: 2020,
      timesPlayed: 0,
      genre: "Pop, Disco",
      artworkPath: "/uploads/dualipa_futurenostalgia.jpg",
    },
    {
      artist: "The Doobie Brothers",
      album: "The Captain and Me",
      year: 1973,
      timesPlayed: 0,
      genre: "Rock, Soft Rock",
      artworkPath: "/uploads/thedoobiebrothers_thecaptainandme.jpg",
    },
    {
      artist: "Early James",
      album: "Strange Time to Be Alive",
      year: 2020,
      timesPlayed: 0,
      genre: "Blues, Folk",
      artworkPath: "/uploads/earlyjames_strangetime.jpg",
    },
    {
      artist: "Elvis Presley",
      album: "Elvis Sings the Wonderful World of Christmas",
      year: 1971,
      timesPlayed: 0,
      genre: "Christmas, Pop",
      artworkPath: "/uploads/elvis_christmas.jpg",
    },
    {
      artist: "Sam Fender",
      album: "Hypersonic Missiles",
      year: 2019,
      timesPlayed: 0,
      genre: "Rock, Indie Rock",
      artworkPath: "/uploads/samfender_hypersonicmissiles.jpg",
    },
    {
      artist: "Peter Frampton",
      album: "I'm in You",
      year: 1977,
      timesPlayed: 0,
      genre: "Rock, Soft Rock",
      artworkPath: "/uploads/peterframpton_iminyou.jpg",
    },
    {
      artist: "A Flock of Seagulls",
      album: "A Flock of Seagulls",
      year: 1982,
      timesPlayed: 0,
      genre: "New Wave, Synthpop",
      artworkPath: "/uploads/aflockofseagulls_selfitled.jpg",
    },
    {
      artist: "Frankie and the Witchfingers",
      album: "2AM",
      year: 2019,
      timesPlayed: 0,
      genre: "Psychedelic Rock, Garage Rock",
      artworkPath: "/uploads/frankieandthewitchfingers_2am.jpg",
    },
    {
      artist: "Daryl Hall & John Oates",
      album: "H2O",
      year: 1982,
      timesPlayed: 0,
      genre: "Pop, Rock",
      artworkPath: "/uploads/halloates_h2o.jpg",
    },
    {
      artist: "George Harrison",
      album: "The Best of George Harrison",
      year: 1976,
      timesPlayed: 0,
      genre: "Rock, Pop",
      artworkPath: "/uploads/georgeharrison_bestof.jpg",
    },
    {
      artist: "Donnie Fritz",
      album: "Oh My Goodness",
      year: 2020,
      timesPlayed: 0,
      genre: "Country, Folk",
      artworkPath: "/uploads/donniefritz_ohmygoodness.jpg",
    },
    {
      artist: "The Jimi Hendrix Experience",
      album: "Smash Hits",
      year: 1968,
      timesPlayed: 0,
      genre: "Rock, Psychedelic Rock",
      artworkPath: "/uploads/jimihendrix_smashhits.jpg",
    },
    {
      artist: "Ben Howard",
      album: "Every Kingdom",
      year: 2011,
      timesPlayed: 0,
      genre: "Folk, Indie Folk",
      artworkPath: "/uploads/benhoward_everykingdom.jpg",
    },
    {
      artist: "Michael Jackson",
      album: "Thriller",
      year: 1982,
      timesPlayed: 0,
      genre: "Pop, R&B",
      artworkPath: "/uploads/michaeljackson_thriller.jpg",
    },
    {
      artist: "Waylon Jennings",
      album: "Greatest Hits",
      year: 1979,
      timesPlayed: 0,
      genre: "Country, Outlaw Country",
      artworkPath: "/uploads/waylonjennings_greatesthits.jpg",
    },
    {
      artist: "Jet",
      album: "Get Born",
      year: 2003,
      timesPlayed: 0,
      genre: "Rock, Garage Rock",
      artworkPath: "/uploads/jet_getborn.jpg",
    },
    {
      artist: "Billy Joel",
      album: "Piano Man",
      year: 1973,
      timesPlayed: 0,
      genre: "Rock, Soft Rock",
      artworkPath: "/uploads/billyjoel_pianoman.jpg",
    },
    {
      artist: "Billy Joel",
      album: "The Stranger",
      year: 1977,
      timesPlayed: 0,
      genre: "Rock, Soft Rock",
      artworkPath: "/uploads/billyjoel_thestranger.jpg",
    },
    {
      artist: "Elton John",
      album: "Goodbye Yellow Brick Road",
      year: 1973,
      timesPlayed: 0,
      genre: "Rock, Pop",
      artworkPath: "/uploads/eltonjohn_goodbyeyellowbrickroad.jpg",
    },
    {
      artist: "Joy Williams",
      album: "The Front Porch",
      year: 2019,
      timesPlayed: 0,
      genre: "Folk, Singer-Songwriter",
      artworkPath: "/uploads/joywilliams_thefrontporch.jpg",
    },
    {
      artist: "King Crimson",
      album: "Three of a Perfect Pair",
      year: 1984,
      timesPlayed: 0,
      genre: "Progressive Rock, Art Rock",
      artworkPath: "/uploads/kingcrimson_threeofaperfectpair.jpg",
    },
    {
      artist: "King Crimson",
      album: "Discipline",
      year: 1981,
      timesPlayed: 0,
      genre: "Progressive Rock, Art Rock",
      artworkPath: "/uploads/kingcrimson_discipline.jpg",
    },
    {
      artist: "King Crimson",
      album: "In the Court of the Crimson King",
      year: 1969,
      timesPlayed: 0,
      genre: "Progressive Rock, Art Rock",
      artworkPath: "/uploads/kingcrimson_inthecourt.jpg",
    },
    {
      artist: "Crumb",
      album: "Jinx",
      year: 2019,
      timesPlayed: 0,
      genre: "Indie Rock, Psychedelic Pop",
      artworkPath: "/uploads/crumb_jinx.jpg",
    },
    {
      artist: "Toro y Moi",
      album: "Live at Fillmore, Miami",
      year: 2020,
      timesPlayed: 0,
      genre: "Indie Pop, Electronic",
      artworkPath: "/uploads/toroymoi_liveatfillmore.jpg",
    },
    {
      artist: "The Lemon Twigs",
      album: "A Dream is All We Know",
      year: 2020,
      timesPlayed: 0,
      genre: "Indie Rock, Power Pop",
      artworkPath: "/uploads/thelemontwigs_adreamisallweknow.jpg",
    },
    {
      artist: "The Lemon Twigs",
      album: "Everything Harmony",
      year: 2020,
      timesPlayed: 0,
      genre: "Indie Rock, Power Pop",
      artworkPath: "/uploads/thelemontwigs_everythingharmony.jpg",
    },
    {
      artist: "Lime Cordiale",
      album: "14 Steps to a Better You",
      year: 2020,
      timesPlayed: 0,
      genre: "Indie Pop, Alternative",
      artworkPath: "/uploads/limecordiale_14steps.jpg",
    },
  ];

  for (const vinyl of vinyls) {
    await prisma.vinyl.create({
      data: vinyl,
    });
  }
}

main()
  .then(async () => {
    await prisma.$disconnect();
  })
  .catch(async (e) => {
    console.error(e);
    await prisma.$disconnect();
    process.exit(1);
  });
